### ISSUE TITLE
本地摄像头一直开着一会儿就没有了

### ISSUE THREAD

**Issue by CSX1991** [c1avie/trtc_demo#1]
iphone8 plus 版本14.0.1

**Comment by CSX1991** [comment]
同测的iphone11 没问题，摄像头打开关闭都正常。但是8p不到十几秒之后就自己摄像头关掉了，点击完关闭再打开之后可以正常显示。

**Comment by CSX1991** [comment]
还有个问题，我两个手机跑同一个项目sdkAppId一致，但是进入同一个会议室，列表没有对方。

**Comment by c1avie** [comment]
检查下两个用户id是不是一样的？

**Comment by CSX1991** [comment]
userid 是自己输入的呀，两个手机肯定是不同的呀

**Comment by c1avie** [comment]
好的，我们定位一下，你可以先试下安卓有没有问题

**Comment by CSX1991** [comment]
没有安卓机，模拟器我试试吧，可能会很慢，明天给你答复

**Comment by c1avie** [comment]
安卓端也需要真机运行，你看下 IOS两个手机都有onEnterRoom的事件回调吗。可以加q：1921017379，我们详细沟通下。
