### ISSUE TITLE
flutter语音聊天室

### ISSUE THREAD

**Issue by kawa23** [c1avie/trtc_demo#10]
flutter有语音聊天室的Demo吗

**Comment by c1avie** [comment]
有的，参考这个。https://github.com/c1avie/TRTCChatSalon

**Comment by kawa23** [comment]
感谢回复，之前有看到语音沙龙这个Demo [https://github.com/c1avie/TRTCChatSalon](https://github.com/c1avie/TRTCChatSalon)，想问的是有没有类似包括麦位管理、低延时语音互动、文字聊天等功能的语音聊天室这样的Flutter Demo，如这里 [https://cloud.tencent.com/document/product/647/45753](https://cloud.tencent.com/document/product/647/45753)，我看到只有iOS 和 Android 版本的，没有 flutter的

**Comment by c1avie** [comment]
这个暂时没有，TRTCChatSalon麦位管理类似clubhouse，文字聊天场景sdk有接口的，只是demo里面没有
