### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by dingzuhua2017** [c1avie/trtc_demo#3]
[!] CocoaPods could not find compatible versions for pod "tencent_trtc_cloud":
      In Podfile:
        tencent_trtc_cloud (from `.symlinks/plugins/tencent_trtc_cloud/ios`)
    Specs satisfying the `tencent_trtc_cloud (from `.symlinks/plugins/tencent_trtc_cloud/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by lexuslin001** [comment]
set your Runner target to higher one, and try again then.

**Comment by dingzuhua2017** [comment]
改到ios 10都是不行

**Comment by dingzuhua2017** [comment]
> Set your Runner target to higher one, and try again then.

改到13了都不行，报一样的错

**Comment by lexuslin001** [comment]
加QQ群了解一下看，788910197

**Comment by c1avie** [comment]
@dingzuhua2017 
可以更新下demo代码，再试下看会不会报错

**Comment by c1avie** [comment]
还不行的话可以试试这里的解决方法：https://github.com/CocoaPods/CocoaPods/issues/9343
![image](https://user-images.githubusercontent.com/2912208/101131470-4d712680-3640-11eb-9b88-f192f619314f.png)
