### ISSUE TITLE
iOS 打包失败

### ISSUE THREAD

**Issue by sldboy** [c1avie/trtc_demo#4]
flutter sdk 1.22    android studio 3.4.1  trtc—sdk版本0.0.6
 ios打包报错：
    <module-includes>:1:1: warning: umbrella header for module 'TXLiteAVSDK_TRTC' does not include header '/cpp_interface/ITRTCCloud.h' [-Wincomplete-umbrella]
    #import "Headers/TXLiteAVSDK.h"
    ^
    <module-includes>:1:1: warning: umbrella header for module 'TXLiteAVSDK_TRTC' does not include header '/cpp_interface/TRTCCode.h' [-Wincomplete-umbrella]
    <module-includes>:1:1: warning: umbrella header for module 'TXLiteAVSDK_TRTC' does not include header '/cpp_interface/TRTCCloudCallback.h' [-Wincomplete-umbrella]
    <module-includes>:1:1: warning: umbrella header for module 'TXLiteAVSDK_TRTC' does not include header '/cpp_interface/TRTCTypeDef.h' [-Wincomplete-umbrella]
    <module-includes>:1:1: warning: umbrella header for module 'TXLiteAVSDK_TRTC' does not include header '/cpp_interface/ITXAudioEffectManager.h' [-Wincomplete-umbrella]
    <module-includes>:1:1: warning: umbrella header for module 'TXLiteAVSDK_TRTC' does not include header '/cpp_interface/ITXDeviceManager.h' [-Wincomplete-umbrella]
    <module-includes>:1:1: warning: umbrella header for module 'TXLiteAVSDK_TRTC' does not include header 'TXLiteAVEncodedDataProcessingListener.h' [-Wincomplete-umbrella]
    <module-includes>:1:1: warning: umbrella header for module 'TXLiteAVSDK_TRTC' does not include header 'TXLiteAVBuffer.h' [-Wincomplete-umbrella]
    8 warnings generated.

**Comment by c1avie** [comment]
参考文档：https://pub.dev/packages/tencent_trtc_cloud
第4点看看
![image](https://user-images.githubusercontent.com/2912208/101347129-8f120380-38c4-11eb-9f4a-ea9cdbc4c256.png)

**Comment by c1avie** [comment]
加qq群788910197 我们了解定位一下
