### ISSUE TITLE
Android 打包报错 .aar file dependencies are not supported

### ISSUE THREAD

**Issue by kimwong0919** [c1avie/trtc_demo#6]
【Android】-【sdk 0.1.6】Flutter 1.22.4

【当前现象】：android打包报错
【是否必现】：必现
【复现方法】：打包
【日志或者描述、截图】：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tencent_trtc_cloud:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :tencent_trtc_cloud project caused this error: E:\flutter\.pub-cache\hosted\pub.flutter-io.cn\tencent_trtc_cloud-0.1.6\android\libs\LiteAVSDK_TRTC_8.2.9809.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

![image](https://user-images.githubusercontent.com/43719624/104395835-8f1cb780-5584-11eb-8e33-74bf4df5f24f.png)

**Comment by shop987** [comment]
是打release包报这个错误吗？执行的flutter build apk -d android-arm64   这个命令吗？

**Comment by kimwong0919** [comment]
> 是打release包报这个错误吗？执行的flutter build apk -d android-arm64 这个命令吗？
是执行flutter run 命令的时候报错

**Comment by c1avie** [comment]
我们稍后会升级个版本解决此问题。可以加qq群快速沟通 788910197

**Comment by c1avie** [comment]
请 发一下你 安卓 grade插件的版本号

**Comment by c1avie** [comment]
@kimwong0919  你可以将build.grade的版本降到3.5.3试下哈

**Comment by kimwong0919** [comment]
> 请 发一下你 安卓 grade插件的版本号

gradle版本是4.1.1

现在使用本地moudle的依赖方式，回报插件丢失的异常

[        ] I/flutter (22038): info date change--->120--21093-->
[  +20 ms] E/flutter (22038): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method sharedInstance on channel trtcCloudChannel)
[        ] E/flutter (22038): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
[        ] E/flutter (22038): <asynchronous suspension>
[        ] E/flutter (22038): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
[        ] E/flutter (22038): #2      TRTCCloud.sharedInstance (package:tencent_trtc_cloud/trtc_cloud.dart:25:22)
[        ] E/flutter (22038): #3      TRTCAgent.init (package:InternetHospital/lib/TRTCAgent.dart:52:33)
[        ] E/flutter (22038): #4      VideoRequestBar.build.<anonymous closure>.<anonymous closure> (package:InternetHospital/components/VideoRequestBar.dart:116:47)
[        ] E/flutter (22038): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
[        ] E/flutter (22038): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
[        ] E/flutter (22038): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
[        ] E/flutter (22038): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
[        ] E/flutter (22038): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
[        ] E/flutter (22038): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
[   +2 ms] E/flutter (22038): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
[        ] E/flutter (22038): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
[        ] E/flutter (22038): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[        ] E/flutter (22038): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[        ] E/flutter (22038): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[        ] E/flutter (22038): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] E/flutter (22038): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] E/flutter (22038): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
[        ] E/flutter (22038): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] E/flutter (22038): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] E/flutter (22038): #21     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] E/flutter (22038): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by kimwong0919** [comment]
> @kimwong0919 你可以将build.grade的版本降到3.5.3试下哈

降低gradle版本是可以，但是我其他依赖又报错了。。。

**Comment by c1avie** [comment]
MissingPluginException，插件丢失这个问题是怎么触发的？

**Comment by kimwong0919** [comment]
> 我们稍后会升级个版本解决此问题。可以加qq群快速沟通 788910197

搜不到群。。。

**Comment by c1avie** [comment]
那加q： 1921017379
