### ISSUE TITLE
同时使用 shared_preferences >=2.0.0 时依赖有冲突

### ISSUE THREAD

**Issue by ManhonSzeto** [c1avie/trtc_demo#8]
同时使用 shared_preferences >=2.0.0 时依赖有冲突

**Comment by c1avie** [comment]
是用的flutter2.0吗

**Comment by ManhonSzeto** [comment]
是的

c1avie ***@***.***> 于 2021年3月12日周五 下午5:14写道：

**Comment by c1avie** [comment]
demo中实际并没有用到 shared_preferences，可以考虑pubspec.yaml文件中去掉。如果实在要用，可以先降低flutter的版本

**Comment by ManhonSzeto** [comment]
有支持flutter 2的时间安排吗

**Comment by c1avie** [comment]
sdk如果不引入shared_preferences的话是支持flutter 2.0的，引入shared_preferences后跟path_provider的版本冲突了。
预计会在4月初解决。如果要用shared_preferences的话，可以先降低shared_preferences的版本。
